### ISSUE TITLE
Golang update

### ISSUE THREAD

**Issue by jabithew** [our-source/restic#2]
Restic 0.9.1 needs a newer version of Go to compile. This can be fixed by changing the first line of the Dockerfile to 

`FROM golang:1.10.3-alpine `

I have pulled this repo and changed this locally and it works well. However, I don't have persmissions to push the change back.

**Comment by johansmitsnl** [comment]
The 0.9.1 uses the go 1.9 language.

https://github.com/restic/restic/blob/a717e9e6f727fb3bdb46556af8bb22284d218db3/.travis.yml#L7

I pushed a new version to use this version.
